### ISSUE TITLE
Try transformer based models

### ISSUE THREAD

**Issue by ayush-1506** [mozilla/bugbug#2608] opened 2021-11-02 18:40 UTC
Slightly out of the loop here, but some classifiers we can try out
- Bert
- RoBERTa
- DistilBERT
- GPT

They've shown promising performance on most text based tasks, might be worth looking into them. (it has also become surprisingly convenient to use pre-training with these models nowadays)

**Comment by marco-c** [comment] 2021-11-08 11:49
I tried DistilBERT out of curiosity for the components model (using the [transformers](https://github.com/huggingface/transformers) library) and it looks promising.

**Comment by marco-c** [comment] 2023-01-17 21:24
Closing as duplicate of #39.

**Closed by marco-c** 2023-01-17 21:24 UTC
