### ISSUE TITLE
Calibrate xgboost regressor model to make it isotonic

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2828] opened 2022-03-17 22:31 UTC
So its output can be interpreted as a confidence level.

**Comment by WhiteWolf47** [comment] 2023-03-07 20:59
@marco-c seems like an interesting issue, I would like to help out and work on this issue :blush: . Can you add a little bit more description so that I can have a btter idea ! :smile:

**Comment by WhiteWolf47** [comment] 2023-03-08 13:30
@marco-c As far as I understand, we are looking to to predict the probability of an observation belonging to each possible class instead of directly  predicting class values directly for a classification problem for the xgboost regressor, right?

**Comment by WhiteWolf47** [comment] 2023-03-08 13:46
@marco-c As far as I understand this, we are lokking to post-process the model's predictions to ensure that they are monotonically increasing. If this is the case then we can use scikit-learn's IsotonicRegression module

**Comment by suhaibmujahid** [comment] 2023-03-08 15:40
> Also, can you please assign this issue to me :)

As stated in [CONTRIBUTING.md](https://github.com/mozilla/bugbug/blob/master/CONTRIBUTING.md), please don't ask to be assigned to an issue or if you can work on an issue, you can work on it without asking, as long as there is no open PR linked to it.




> @marco-c As far as I understand this, we are lokking to post-process the model's predictions to ensure that they are monotonically increasing. If this is the case then we can use scikit-learn's IsotonicRegression module

The goal here is to perform calibration of the probabilities output by XGBoost. In this context, scikit-learn's IsotonicRegression can be used.

**Comment by WhiteWolf47** [comment] 2023-03-08 15:49
> > Also, can you please assign this issue to me :)
> 
> As stated in [CONTRIBUTING.md](https://github.com/mozilla/bugbug/blob/master/CONTRIBUTING.md), please don't ask to be assigned to an issue or if you can work on an issue, you can work on it without asking, as long as there is no open PR linked to it.
> 
> > @marco-c As far as I understand this, we are lokking to post-process the model's predictions to ensure that they are monotonically increasing. If this is the case then we can use scikit-learn's IsotonicRegression module
> 
> The goal here is to perform calibration of the probabilities output by XGBoost. In this context, scikit-learn's IsotonicRegression can be used.

In which file we are calculating the probabilities from the XGBoost model?

**Comment by WhiteWolf47** [comment] 2023-03-08 16:50
@suhaibmujahid I tried something but i'm unable to push changes to my fork. Its showing - "fatal: unable to get credential storage lock in 1000 ms: No such file or directory
Everything up-to-date"
Also before pushing when I commited those changes , pre-commit is showing "flake8" as failed and the error is "bugbug/model.py:469:9: F841 local variable 'mse' is assigned to but never used"
'mse' is the mean squared error of the calibrated model

**Comment by suhaibmujahid** [comment] 2023-03-08 17:11
> @suhaibmujahid I tried something but i'm unable to push changes to my fork. Its showing - "fatal: unable to get credential storage lock in 1000 ms: No such file or directory Everything up-to-date" 

This looks like a git problem.

> Also before pushing when I commited those changes , pre-commit is showing "flake8" as failed and the error is "bugbug/model.py:469:9: F841 local variable 'mse' is assigned to but never used" 'mse' is the mean squared error of the calibrated model

It is a lint error, you cannot commit unused variables.

**Closed** 2023-04-20 17:15 UTC
