### ISSUE TITLE
Restrict the training set of the StepsToReproduce model only to defects

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#792] opened 2019-07-26 12:49 UTC
Given that STRs don't apply to enhancement or task.

**Comment by sosa-e** [comment] 2023-04-10 15:04
Hello! I am new to open source and am currently working on this bug after following the steps outlined in #1092 . I read through #817 and have some questions. May I post questions in this issue?

**Comment by suhaibmujahid** [comment] 2023-04-10 16:54
> Hello! I am new to open source and am currently working on this bug after following the steps outlined in #1092 . I read through #817 and have some questions. May I post questions in this issue?

Welcome, @sosa-e! You can post questions related to the issues here. Also, you can chat with us in the [bugbug](https://chat.mozilla.org/#/room/#bugbug:mozilla.org) Matrix room.

**Comment by naoya2000** [comment] 2023-12-03 09:44
Turns out that there is an issue; I tried to use the model to classify a certain bug but it didn't work. However, it seems like that there are some steps that may help in the [Discussion](https://github.com/mozilla/bugbug/discussions/3338) so I will try those out first. Thanks!
`
(base) naoyaokamoto@Naoyas-MacBook-Air-393 bugbug % python3 -m scripts.bug_classifier stepstoreproduce --bug-id 1635837                                        
2023-12-03 18:38:17,677:INFO:numexpr.utils:NumExpr defaulting to 8 threads.
2023-12-03 18:38:19,688:INFO:__main__:stepstoreproducemodel does not exist. Downloading the model....
2023-12-03 18:38:19,703:INFO:bugbug.utils:Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.bugbug.train_stepstoreproduce.latest/artifacts/public/stepstoreproducemodel.tar.zst...
tar: Error inclusion pattern: Failed to open 'zstdmt'
2023-12-03 18:38:21,680:WARNING:bugbug.utils:Command '['tar', '-I', 'zstdmt', '-xf', 'stepstoreproducemodel.tar.zst']' returned non-zero exit status 1.. Falling back to zstandard API, which could be slower.
Traceback (most recent call last):
  File "/Users/naoyaokamoto/mambaforge/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/naoyaokamoto/mambaforge/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/naoyaokamoto/Documents/GitHub/bugbug/scripts/bug_classifier.py", line 80, in <module>
    main()
  File "/Users/naoyaokamoto/Documents/GitHub/bugbug/scripts/bug_classifier.py", line 76, in main
    classify_bugs(args.model, args.bug_id)
  File "/Users/naoyaokamoto/Documents/GitHub/bugbug/scripts/bug_classifier.py", line 32, in classify_bugs
    model = model_class.load(model_file_name)
  File "/Users/naoyaokamoto/Documents/GitHub/bugbug/bugbug/model.py", line 593, in load
    model.clf.named_steps["estimator"].load_model(xgboost_model_path)
AttributeError: 'XGBClassifier' object has no attribute 'named_steps'
`

**Comment by marco-c** [comment] 2023-12-03 10:48
> However, I got the following result stating that the imblearn.pipeline.Pipeline model isn't supported by TreeExplainer. Can I safely ignore this, or do I have to resolve this issue first before working on the rest of the issue? Thanks!

@suhaibmujahid maybe a regression from your recent changes?

**Comment by suhaibmujahid** [comment] 2023-12-03 17:48
> Can I safely ignore this

@naoya2000 yes, you can ignore it. You can disable this until the issue is fixed by setting `self.calculate_importance` to `False` in the model constructer (do not commit this in your PR). 

> maybe a regression from your recent changes?

@marco-c Yes, it is a regression. I filed #3880 to follow up on this.

**Comment by naoya2000** [comment] 2023-12-05 07:13
I just want to see that I'm on the right track here; basically I need to write something so that the only bugs in the training set are those with `type` set to `defect`. So I think I would need to go into `stepstoreproduce.py` in the `models` folder and then in the `get_labels` function, I would want to write something that basically checks that the bug `type` is `defect`. Or, perhaps I shouldn't be focusing on `stepstoreproduce.py` but rather `trainer.py`?

**Closed** 2024-01-02 17:43 UTC
Labels: good-first-bug
